#Docker関係の設定は全て https://qiita.com/three_mouth_ago/items/b7c54ae1b0f831060a70 を参考

services:
  web:
    build: .
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - .:/tagfoto
    depends_on:
      - db
    links:
      - db
    environment:
      RAILS_ENV: development
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: db

  db:
    platform: linux/x86_64
    restart: always
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    restart: always
    depends_on:
      - web 

volumes:
  mysql-data: