# アプリごとにやること一覧。

# ここのwebのポート3箇所
# ここのドメイン2箇所
# Procfile.devのポート1箇所
# puma.rbのポート2箇所
# master.keyをローカルからコピペ

services:
  web:
    build: .
    volumes:
      - .:/tagfoto
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: password
      VIRTUAL_HOST: tagfoto.bnbnb.link
      VIRTUAL_PORT: 3000 
      LETSENCRYPT_HOST: tagfoto.bnbnb.link
      LETSENCRYPT_EMAIL: pulpfictiontaxidriver@yahoo.co.jp

  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      TZ: "Asia/Tokyo"
    ports:
      - 3307:3307
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:

networks:
  default:
    external:
      name: shared
    

