version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.0
  aws-ecs: circleci/aws-ecs@3.2.0
  aws-cli: circleci/aws-cli@3.1.1

executors:
  ubuntu-executor:
    machine:
      image: ubuntu-2004:current  

workflows:

  rails:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: '${MY_APP_PREFIX}-rails'
          tag: '${CIRCLE_SHA1}'
          executor: ubuntu-executor
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: '${MY_APP_PREFIX}-svc'
          cluster: '${MY_APP_PREFIX}-clst'
          container-image-name-updates: 'container=rails,tag=${CIRCLE_SHA1}'

  nginx:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: '${MY_APP_PREFIX}-nginx'
          tag: '${CIRCLE_SHA1}'
          executor: ubuntu-executor
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: '${MY_APP_PREFIX}-svc'
          cluster: '${MY_APP_PREFIX}-clst'
          container-image-name-updates: 'container=nginx,tag=${CIRCLE_SHA1}'