version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15
  aws-ecs: circleci/aws-ecs@2.0.0

workflows:
  image-build:
    jobs:
      executor: aws-ecs/default
      steps:
        - checkout

        - setup_remote_docker:
            version: 20.10.8

        - run:
            name: Build Docker images
            command: docker-compose build

  nginx-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          repo: ${MY_APP_PREFIX}-nginx
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: main
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: '${MY_APP_PREFIX}2'
          cluster-name: '${MY_APP_PREFIX}-clst'
          service-name: '${MY_APP_PREFIX}-svc'
          container-image-name-updates: "container=nginx,tag=${CIRCLE_SHA1}"

  rails-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          repo: ${MY_APP_PREFIX}-rails
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: main
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: '${MY_APP_PREFIX}2'
          cluster-name: '${MY_APP_PREFIX}-clst'
          service-name: '${MY_APP_PREFIX}-svc'
          container-image-name-updates: "container=rails,tag=${CIRCLE_SHA1}"