default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

development:
  <<: *default
  database: tagfoto_development

test:
  <<: *default
  database: tagfoto_test

production:
  <<: *default
  database: tagfoto_production
  url: <%= ENV['DATABASE_URL']&.sub(/\Amysql/, 'mysql2') %>
